In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_pickle('./data/preprocessed_data.pkl')
df.head()

                                                       ZnO                \
                                                         1             2
scent_name trial_num on_off_state Time (sec)
Heptanol   0         on           0.000009    7.740000e-10  3.028200e-07
                                  2.981646    1.150800e-08  2.955960e-07
                                  5.951279    1.164000e-08  2.985380e-07
                                  8.889494    1.139700e-08  3.051830e-07
                                  11.895487   8.972000e-09  2.375300e-07

                                                                SnO2  \
                                                         3         1
scent_name trial_num on_off_state Time (sec)
Heptanol   0         on           0.000009    1.332600e-08  0.000072
                                  2.981646    1.503100e-08  0.000072
                                  5.951279    1.300000e-08  0.000073
                                  8.889494    1.305800e-08  0.000073
                                  11.895487   7.302000e-09  0.000073

                                                                  \
                                                     2         3
scent_name trial_num on_off_state Time (sec)
Heptanol   0         on           0.000009    0.000065  0.000053
                                  2.981646    0.000064  0.000054
                                  5.951279    0.000065  0.000054
                                  8.889494    0.000065  0.000054
                                  11.895487   0.000066  0.000055

                                                       AZO            \
                                                         1         2
scent_name trial_num on_off_state Time (sec)
Heptanol   0         on           0.000009    1.267340e-07  0.000001
                                  2.981646    1.277770e-07  0.000001
                                  5.951279    1.306230e-07  0.000001
                                  8.889494    1.175820e-07  0.000001
                                  11.895487   1.184220e-07  0.000001


                                                         3
scent_name trial_num on_off_state Time (sec)
Heptanol   0         on           0.000009    4.576990e-07
                                  2.981646    5.968640e-07
                                  5.951279    5.696490e-07
                                  8.889494    5.729060e-07
                                  11.895487   5.641550e-07

In [3]:
by_scent = df.loc["Heptanol"]
by_scent

                                              ZnO                              \
                                                1             2             3
trial_num on_off_state Time (sec)
0         on           0.000009      7.740000e-10  3.028200e-07  1.332600e-08
                       2.981646      1.150800e-08  2.955960e-07  1.503100e-08
                       5.951279      1.164000e-08  2.985380e-07  1.300000e-08
                       8.889494      1.139700e-08  3.051830e-07  1.305800e-08
                       11.895487     8.972000e-09  2.375300e-07  7.302000e-09
...                                           ...           ...           ...
11        on           20811.378324  1.416000e-08  2.425700e-07  1.559200e-08
                       20814.387244  1.684000e-08  2.796200e-07  1.222800e-08
                       20817.388022  1.315500e-08  2.147550e-07  2.374100e-08
                       20820.404342  1.562500e-08  2.394680e-07  7.314000e-09
                       20823.416638  1.898300e-08           NaN           NaN

                                         SnO2                      \
                                            1         2         3
trial_num on_off_state Time (sec)
0         on           0.000009      0.000072  0.000065  0.000053
                       2.981646      0.000072  0.000064  0.000054
                       5.951279      0.000073  0.000065  0.000054
                       8.889494      0.000073  0.000065  0.000054
                       11.895487     0.000073  0.000066  0.000055
...                                       ...       ...       ...
11        on           20811.378324  0.000046  0.000033  0.000023
                       20814.387244  0.000046  0.000033  0.000023
                       20817.388022  0.000045  0.000033  0.000023
                       20820.404342  0.000045  0.000033  0.000022
                       20823.416638       NaN       NaN       NaN

                                              AZO
                                                1             2             3
trial_num on_off_state Time (sec)
0         on           0.000009      1.267340e-07  1.125030e-06  4.576990e-07
                       2.981646      1.277770e-07  1.244120e-06  5.968640e-07
                       5.951279      1.306230e-07  1.278440e-06  5.696490e-07
                       8.889494      1.175820e-07  1.284060e-06  5.729060e-07
                       11.895487     1.184220e-07  1.281620e-06  5.641550e-07
...                                           ...           ...           ...
11        on           20811.378324  9.812700e-08  2.954870e-07  2.393610e-07
                       20814.387244  1.015750e-07  2.860320e-07  2.260690e-07
                       20817.388022  1.061030e-07  2.776210e-07  2.313090e-07
                       20820.404342  9.745300e-08  2.927320e-07  2.392860e-07
                       20823.416638           NaN           NaN           NaN

[6873 rows x 9 columns]

In [4]:
data = by_scent.droplevel("on_off_state")

In [5]:
scents = df.index.map(lambda x: x[0]).unique()
scents

Index(['Heptanol', '2-ethylfenchol', 'Octanal', 'Eugenol', 'Cis-3-hexenol',
       'Decanal', '2,3,5 trymethylpyrazine', 'Geraniol'],
      dtype='object')

In [6]:
trials = []
for i in scents:
    trials.append(df.loc[i].index.max()[0])
trials

[11, 11, 11, 6, 6, 6, 8, 6]

In [7]:
data = np.zeros((sum(trials)-8, 530, 9))
label = []
count = 0
for i in range(8):
    print(scents[i])
    for j in range(1, trials[i]):
        count += 1
        label.append(i)
        temp = df.loc[scents[i], j]
        print(len(temp))
        temp = temp.to_numpy()[:530]
        data[count] = temp

Heptanol
597
596
595
594
594
594
593
593
593
592
2-ethylfenchol
599
598
597
597
596
596
594
592
589
590
Octanal
597
598
596
593
592
594
596
593
592
591
Eugenol
598
598
598
597
597
Cis-3-hexenol
597
598
596
592
589
Decanal
598
598
597
598
597
2,3,5 trymethylpyrazine
592
584
589
584
576
584
576
Geraniol
601
599
597
598
597

C:\Users\ansck\anaconda3\lib\site-packages\ipykernel_launcher.py:9: PerformanceWarning: indexing past lexsort depth may impact performance.
  if __name__ == '__main__':

IndexError: index 57 is out of bounds for axis 0 with size 57

In [ ]:
data.shape
X = data.reshape(57, -1)
y = np.array(label)
y = tf.keras.utils.to_categorical(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.0, random_state=42)

In [ ]:
import tensorflow as tf
nb_classes = 8
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(100, activation = 'relu'),
#     tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(100, activation = 'relu'),
    tf.keras.layers.Dense(100, activation = 'relu'),
#     tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(nb_classes, activation = 'softmax'),
 ])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(X_train, y_train,
                    epochs=30,
                    validation_data=(X_train, y_train),
                    )

In [ ]:
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(len(acc))

plt.plot(epochs, acc, 'r', label='Training accuracy')
plt.plot(epochs, val_acc, 'b', label='Validation accuracy')
plt.title('Training and validation accuracy')
plt.legend(loc=0)
plt.figure()
plt.show()

plt.plot(epochs, loss, 'r', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend(loc=0)
plt.figure()
plt.show()

In [ ]:
y_train